name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker build -t sofakorra/laba5:tagname .
          docker push sofakorra/laba5:tagname

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pull image from DockerHub
        run: docker pull sofakorra/laba5:tagname

      - name: Run tests in Docker container
        run: docker run sofakorra/laba5:tagname
